apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-dep
  labels:
    app: web-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-site
  template:
    metadata:
      labels:
        app: web-site
    spec:
      containers:
        - name: app-cointainer
          image: 475149/particle41:1
          ports:
            - name: myapp-port
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-srv
spec:
  type: NodePort
  ports:
    - port: 3000
      nodePort: 30001
      targetPort: 8080
      protocol: TCP
  selector:
    app: web-site
